import { FeedEvent } from '@/features/home/_types';

export const MOCK_COMMUNITY_FEED: FeedEvent[] = [
  {
    id: '1',
    type: 'pull_request',
    author: { login: 'torvalds', avatarURL: '', displayName: 'Linus Torvalds' },
    repoOwner: 'torvalds',
    repoName: 'linux',
    title: 'Merge branch \'x86/urgent\' from tip tree',
    body: 'Pull x86 fixes from Borislav:\n"A couple of fixes for the x86 boot sequence..."',
    likeCount: 142,
    commentCount: 23,
    timeAgo: '2h ago',
  },
  {
    id: '2',
    type: 'issue',
    author: { login: 'gvanrossum', avatarURL: '', displayName: 'Guido van Rossum' },
    repoOwner: 'python',
    repoName: 'cpython',
    title: 'Add new syntax for type parameter defaults in PEP 696',
    body: 'This implements the new TypeVar default syntax discussed in the steering council meeting.',
    likeCount: 89,
    commentCount: 11,
    timeAgo: '4h ago',
  },
  {
    id: '3',
    type: 'release',
    author: { login: 'yyx990803', avatarURL: '', displayName: 'Evan You' },
    repoOwner: 'vuejs',
    repoName: 'core',
    title: 'v3.4.21 — Vapor mode performance improvements',
    body: 'This release includes significant performance improvements to the Vapor mode compiler.',
    likeCount: 310,
    commentCount: 45,
    timeAgo: '6h ago',
  },
  {
    id: '4',
    type: 'commit',
    author: { login: 'tj', avatarURL: '', displayName: 'TJ Holowaychuk' },
    repoOwner: 'apex',
    repoName: 'log',
    title: 'feat: add structured JSON output format',
    body: 'Adds a new structured JSON handler for production log output with optional pretty printing.',
    likeCount: 54,
    commentCount: 7,
    timeAgo: '8h ago',
  },
  {
    id: '5',
    type: 'pull_request',
    author: { login: 'addyosmani', avatarURL: '', displayName: 'Addy Osmani' },
    repoOwner: 'GoogleChrome',
    repoName: 'lighthouse',
    title: 'perf: reduce bundle size by 40% via tree shaking audit modules',
    body: 'This PR implements aggressive tree shaking across all audit modules, reducing the final bundle size significantly.',
    likeCount: 201,
    commentCount: 19,
    timeAgo: '12h ago',
  },
];

export const MOCK_FOR_YOU_FEED: FeedEvent[] = [
  {
    id: '6',
    type: 'pull_request',
    author: { login: 'bholmesdev', avatarURL: '', displayName: 'Ben Holmes' },
    repoOwner: 'withastro',
    repoName: 'astro',
    title: 'feat(content): add experimental content layer API',
    body: 'Introduces a new content layer API that allows arbitrary data sources to be used as content collections.',
    likeCount: 178,
    commentCount: 32,
    timeAgo: '1h ago',
  },
  {
    id: '7',
    type: 'issue',
    author: { login: 'nicolo-ribaudo', avatarURL: '', displayName: 'Nicolo Ribaudo' },
    repoOwner: 'babel',
    repoName: 'babel',
    title: 'Bug: decorators transform breaks class fields in edge case',
    body: 'When combining @injectable decorator with private class fields, the transform incorrectly reorders initialization.',
    likeCount: 43,
    commentCount: 8,
    timeAgo: '3h ago',
  },
  {
    id: '8',
    type: 'release',
    author: { login: 'Rich-Harris', avatarURL: '', displayName: 'Rich Harris' },
    repoOwner: 'sveltejs',
    repoName: 'svelte',
    title: 'Svelte 5.0.0-next.200 — runes stabilization',
    body: 'Another step toward the Svelte 5 stable release. Runes API is now considered stable.',
    likeCount: 512,
    commentCount: 67,
    timeAgo: '5h ago',
  },
];

export const MOCK_AGENTS_FEED: FeedEvent[] = [
  {
    id: '9',
    type: 'pull_request',
    author: { login: 'anthropics', avatarURL: '', displayName: 'Anthropic' },
    repoOwner: 'anthropics',
    repoName: 'claude-code',
    title: 'feat: add parallel tool execution support',
    body: 'Enables Claude to run multiple independent tool calls concurrently, dramatically reducing latency for complex tasks.',
    likeCount: 892,
    commentCount: 104,
    timeAgo: '30m ago',
  },
  {
    id: '10',
    type: 'issue',
    author: { login: 'hwchase17', avatarURL: '', displayName: 'Harrison Chase' },
    repoOwner: 'langchain-ai',
    repoName: 'langchain',
    title: 'feat: LangGraph Studio — visual agent debugging tool',
    body: 'Adds a new visual debugging interface for LangGraph agents, making it easier to inspect state transitions.',
    likeCount: 634,
    commentCount: 88,
    timeAgo: '2h ago',
  },
  {
    id: '11',
    type: 'release',
    author: { login: 'microsoft', avatarURL: '', displayName: 'Microsoft' },
    repoOwner: 'microsoft',
    repoName: 'autogen',
    title: 'AutoGen v0.4 — async-first multi-agent framework',
    body: 'Complete rewrite with async-first design, improved agent coordination, and new human-in-the-loop patterns.',
    likeCount: 1204,
    commentCount: 156,
    timeAgo: '4h ago',
  },
];

export const FEED_BY_TAB = {
  community: MOCK_COMMUNITY_FEED,
  forYou: MOCK_FOR_YOU_FEED,
  agents: MOCK_AGENTS_FEED,
} as const;
