import type { HomeFeedEvent, CommunityPost, RepoTag } from '@/features/home/_types';

const DEFAULT_NARRATION = {
  body: '',
  event_description: null,
  detected_agent: null,
  human_ratio: 1,
  agent_ratio: 0,
};

export const MOCK_COMMUNITY_FEED: CommunityPost[] = [
  {
    id: '1',
    author_login: 'torvalds',
    author_name: 'Linus Torvalds',
    author_avatar: null,
    body: 'Just merged the x86/urgent branch. A couple of fixes for the boot sequence that were causing issues on newer hardware.',
    visibility: 'public',
    repo_tags: [{ owner: 'torvalds', name: 'linux', is_private: false }] as RepoTag[],
    image_urls: [],
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    deleted_at: null,
    like_count: 142,
    liked: false,
    comment_count: 23,
    quoted_event_key: null,
    quoted_post_id: null,
  },
  {
    id: '2',
    author_login: 'gvanrossum',
    author_name: 'Guido van Rossum',
    author_avatar: null,
    body: 'PEP 696 is moving forward! TypeVar defaults will make generic programming in Python much more ergonomic.',
    visibility: 'public',
    repo_tags: [{ owner: 'python', name: 'cpython', is_private: false }] as RepoTag[],
    image_urls: [],
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    deleted_at: null,
    like_count: 89,
    liked: false,
    comment_count: 11,
    quoted_event_key: null,
    quoted_post_id: null,
  },
  {
    id: '3',
    author_login: 'yyx990803',
    author_name: 'Evan You',
    author_avatar: null,
    body: 'Vue 3.4.21 is out with significant Vapor mode performance improvements. The compiler is now 2x faster for large templates.',
    visibility: 'public',
    repo_tags: [{ owner: 'vuejs', name: 'core', is_private: false }] as RepoTag[],
    image_urls: [],
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    deleted_at: null,
    like_count: 310,
    liked: false,
    comment_count: 45,
    quoted_event_key: null,
    quoted_post_id: null,
  },
];

export const MOCK_FOR_YOU_FEED: HomeFeedEvent[] = [
  {
    id: 'pr-6',
    type: 'pull_request',
    github_id: '6',
    author: { login: 'bholmesdev', avatar_url: null },
    repo_owner: 'withastro',
    repo_name: 'astro',
    title: 'feat(content): add experimental content layer API',
    body: 'Introduces a new content layer API that allows arbitrary data sources to be used as content collections.',
    narration: { ...DEFAULT_NARRATION, body: 'Introduces a new content layer API that allows arbitrary data sources to be used as content collections.' },
    additions: 1243,
    deletions: 87,
    files_changed: 24,
    comments: 32,
    event_created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'issue-7',
    type: 'issue',
    github_id: '7',
    author: { login: 'nicolo-ribaudo', avatar_url: null },
    repo_owner: 'babel',
    repo_name: 'babel',
    title: 'Bug: decorators transform breaks class fields in edge case',
    body: 'When combining @injectable decorator with private class fields, the transform incorrectly reorders initialization.',
    narration: { ...DEFAULT_NARRATION, body: 'Decorator transform incorrectly reorders class field initialization when combined with private fields.' },
    additions: 0,
    deletions: 0,
    files_changed: 0,
    comments: 8,
    event_created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'release-8',
    type: 'release',
    github_id: '8',
    author: { login: 'Rich-Harris', avatar_url: null },
    repo_owner: 'sveltejs',
    repo_name: 'svelte',
    title: 'Svelte 5.0.0-next.200 — runes stabilization',
    body: 'Another step toward the Svelte 5 stable release. Runes API is now considered stable.',
    narration: { ...DEFAULT_NARRATION, body: 'Runes API stabilized in this milestone release, marking a key step toward Svelte 5 stable.' },
    additions: 5420,
    deletions: 2100,
    files_changed: 89,
    comments: 67,
    event_created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_AGENTS_FEED: HomeFeedEvent[] = [
  {
    id: 'pr-9',
    type: 'pull_request',
    github_id: '9',
    author: { login: 'anthropics', avatar_url: null },
    repo_owner: 'anthropics',
    repo_name: 'claude-code',
    title: 'feat: add parallel tool execution support',
    body: 'Enables Claude to run multiple independent tool calls concurrently, dramatically reducing latency for complex tasks.',
    narration: { ...DEFAULT_NARRATION, body: 'Adds parallel tool execution, reducing latency for complex multi-tool tasks.', detected_agent: 'claude', agent_ratio: 0.8, human_ratio: 0.2 },
    additions: 3200,
    deletions: 450,
    files_changed: 42,
    comments: 104,
    event_created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'issue-10',
    type: 'issue',
    github_id: '10',
    author: { login: 'hwchase17', avatar_url: null },
    repo_owner: 'langchain-ai',
    repo_name: 'langchain',
    title: 'feat: LangGraph Studio — visual agent debugging tool',
    body: 'Adds a new visual debugging interface for LangGraph agents, making it easier to inspect state transitions.',
    narration: { ...DEFAULT_NARRATION, body: 'New visual debugging interface for LangGraph agents with state transition inspection.' },
    additions: 0,
    deletions: 0,
    files_changed: 0,
    comments: 88,
    event_created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'release-11',
    type: 'release',
    github_id: '11',
    author: { login: 'microsoft', avatar_url: null },
    repo_owner: 'microsoft',
    repo_name: 'autogen',
    title: 'AutoGen v0.4 — async-first multi-agent framework',
    body: 'Complete rewrite with async-first design, improved agent coordination, and new human-in-the-loop patterns.',
    narration: { ...DEFAULT_NARRATION, body: 'Major rewrite with async-first architecture and improved multi-agent coordination patterns.' },
    additions: 18500,
    deletions: 12300,
    files_changed: 210,
    comments: 156,
    event_created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
];

export const FEED_BY_TAB = {
  community: MOCK_COMMUNITY_FEED,
  forYou: MOCK_FOR_YOU_FEED,
  agents: MOCK_AGENTS_FEED,
} as const;
