# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Build iOS app for staging environment"
  lane :staging do
    build_app(
      scheme: "ExpoBoilerplate-Staging",
      workspace: "ExpoBoilerplate.xcworkspace",
      configuration: "Staging",
      export_method: "ad-hoc",
      output_directory: "./build",
      output_name: "ExpoBoilerplate-staging.ipa"
    )
  end

  desc "Build iOS app for production environment"
  lane :production do
    increment_build_number(xcodeproj: "ExpoBoilerplate.xcodeproj")

    build_app(
      scheme: "ExpoBoilerplate",
      workspace: "ExpoBoilerplate.xcworkspace",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "ExpoBoilerplate-production.ipa"
    )
  end

  desc "Upload production to TestFlight"
  lane :beta do
    production
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Upload production to App Store"
  lane :release do
    production
    upload_to_app_store(
      force: true,
      submit_for_review: false
    )
  end

  desc "Run tests"
  lane :test do
    run_tests(
      scheme: "ExpoBoilerplate",
      workspace: "ExpoBoilerplate.xcworkspace"
    )
  end

  desc "Update certificates"
  lane :certificates do
    match(
      type: "adhoc",
      readonly: true
    )
    match(
      type: "appstore",
      readonly: true
    )
  end

  desc "Clean build"
  lane :clean do
    clear_derived_data
  end
end
